<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Address</name>
   <tag></tag>
   <elementGuidId>3f32ed55-e570-49cc-b13e-9697ca5c7935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Please provide an address.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>01a640f7-41c3-410c-b43f-e9fc9422f735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>f33b86f5-3996-4af4-b448-3df5a7f65828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>matautosizeminrows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e231fa7b-ab85-4626-8858-046d1c8c1aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>matautosizemaxrows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>66be9de5-c9bd-48a1-a1b4-a7c0d9910a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>19e437ec-0ed1-4484-8600-4110cb3b635e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>160</value>
      <webElementGuid>b675ffd9-0da9-4b5e-a7b0-b393ada7df8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c21-19 ng-untouched cdk-text-field-autofill-monitored ng-dirty ng-valid</value>
      <webElementGuid>d71f99a4-94b8-4fae-8f61-f02e499bfe42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please provide an address.</value>
      <webElementGuid>6f557a90-6a6a-40e8-a3aa-e7c1fad0e192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-hint-1 mat-hint-2</value>
      <webElementGuid>77c79338-d72c-42e9-8cf9-c6d0cd27d861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Please provide an address.</value>
      <webElementGuid>4d092c78-87cb-4c4a-8d7e-ab13a3b261b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f3ecd698-6e72-431f-86b7-46e022b260be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>097ed2e7-105b-493a-98ce-d2d7b772b584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address&quot;)</value>
      <webElementGuid>7c3138e7-891b-4ec0-b7e4-0848aed875d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='address']</value>
      <webElementGuid>68b80433-2744-47f7-95ef-29246650c140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='address-form']/mat-form-field[5]/div/div/div[3]/textarea</value>
      <webElementGuid>ab3b8852-320d-4744-9d16-abce59c61d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a8f4436d-10bd-4869-8c59-d9ca146059c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'address' and @placeholder = 'Please provide an address.']</value>
      <webElementGuid>42548bcc-5eb7-4b5b-881e-0f9f58094d1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
