<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txterror_Email-Blank</name>
   <tag></tag>
   <elementGuidId>23e436d2-1376-436a-9e7b-74ab72cf8a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-error-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-error-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Please provide an email address.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>235abbc1-485c-4925-8a0d-d08e41e424f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>96e6757e-9f83-4de3-86e3-1451076519e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error ng-tns-c21-11 ng-star-inserted</value>
      <webElementGuid>42be6c47-94a4-421b-899b-6cd8229a2123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>ac6bb5b8-67df-4abd-99a7-a4cc963eedf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-3</value>
      <webElementGuid>1efb242c-cab8-4d56-82d4-b7cca8c2650c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please provide an email address.</value>
      <webElementGuid>6313a245-0099-49b8-acfa-71a17e5e42ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-3&quot;)</value>
      <webElementGuid>c43c636d-84ad-4c98-8f4a-c678412a0d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-3']</value>
      <webElementGuid>d65eaf93-1378-4e37-9a93-06d20c83ab34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form']/mat-form-field/div/div[2]/div/mat-error</value>
      <webElementGuid>96f32f23-f84b-4c8d-a596-f397acbfe634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::mat-error[1]</value>
      <webElementGuid>1ba7a4e3-b10a-4d7d-b711-b6072f223278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::mat-error[1]</value>
      <webElementGuid>51ed353a-d9e9-43aa-95d3-fc5534a409b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>b6f035c4-5902-45b0-8d25-8dc7bd83d2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please provide a password.'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>5754ba31-d403-49a7-82b2-ab22193f23ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please provide an email address.']/parent::*</value>
      <webElementGuid>6f322e81-c69b-45a8-bec0-bd7eac5d6cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-error</value>
      <webElementGuid>6eba9597-106a-4837-952d-5550c29b6147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-3' and (text() = 'Please provide an email address.' or . = 'Please provide an email address.')]</value>
      <webElementGuid>8207e558-a111-4d7e-a696-1af0fb6fb671</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
