<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio-btn_Payment-Card</name>
   <tag></tag>
   <elementGuidId>0fab11ea-4018-4c1a-b23d-64af5b226620</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-radio-inner-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-radio-button[@id='mat-radio-49']/label/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.mat-radio-inner-circle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38daf9a6-1eb7-4b53-a9e8-c16f3fba24b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-radio-inner-circle</value>
      <webElementGuid>ea023ea2-122f-483e-850e-784d88f38018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-radio-49&quot;)/label[@class=&quot;mat-radio-label&quot;]/span[@class=&quot;mat-radio-container&quot;]/span[@class=&quot;mat-radio-inner-circle&quot;]</value>
      <webElementGuid>01b73757-5151-407c-8597-cd2d7d101159</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-radio-button[@id='mat-radio-49']/label/span/span[2]</value>
      <webElementGuid>7c36fea4-d3e0-467b-9ccb-d33e89931e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span/span[2]</value>
      <webElementGuid>35d6682e-2732-495f-a5e6-225075b9acd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
