<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Orders-Payment</name>
   <tag></tag>
   <elementGuidId>75b57542-6d24-4d69-ad60-b36fbb01746a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-0']/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-menu-trigger.mat-menu-item.mat-menu-item-submenu-trigger.ng-star-inserted.ng-tns-c122-2.mat-menu-item-highlighted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot;Show Orders and Payment Menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcbbd89e-cb6b-4ef4-bf11-0296f810a3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show Orders and Payment Menu</value>
      <webElementGuid>e99b3b25-c506-425d-91ec-a62e607cb29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger mat-menu-item mat-menu-item-submenu-trigger ng-star-inserted ng-tns-c122-2 mat-menu-item-highlighted</value>
      <webElementGuid>253239e2-a151-4207-afa3-cf41623df431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>b3022fad-7979-4ba3-a5ec-3f47f2b81cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c819e09d-6410-4374-9273-403162b5a505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6ad9acf4-5a77-4b46-88a3-47be40b847f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>d1625092-00f3-4d6f-8710-ca2902faeea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fba22b80-5ac2-43db-ba82-0fa1328160f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mat-menu-panel-3</value>
      <webElementGuid>d20c7492-1684-4124-aed2-ae1ce3c8c418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> check_circle_outline  Orders &amp; Payment </value>
      <webElementGuid>beb4c79c-55d2-4540-80d8-b54ac5f00e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-0&quot;)/div[@class=&quot;mat-menu-content ng-tns-c122-2&quot;]/button[@class=&quot;mat-focus-indicator mat-menu-trigger mat-menu-item mat-menu-item-submenu-trigger ng-star-inserted ng-tns-c122-2 mat-menu-item-highlighted&quot;]</value>
      <webElementGuid>040aef2c-9252-4d3b-be60-5433621d1786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-0']/div/button[2]</value>
      <webElementGuid>025ae88d-4579-402e-8e89-bcde98d339be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jessica1@gmail.com'])[2]/following::button[1]</value>
      <webElementGuid>b3462544-86e1-433c-a026-6d8ba67686c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[1]/following::button[4]</value>
      <webElementGuid>d0a1806a-d018-4e3c-8fd1-b2b593e58e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy &amp; Security'])[2]/preceding::button[1]</value>
      <webElementGuid>5f88fd40-e511-4534-964f-5ab183a190b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/button[2]</value>
      <webElementGuid>e7311526-9292-454b-9743-f7dffc6cbf1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' check_circle_outline  Orders &amp; Payment ' or . = ' check_circle_outline  Orders &amp; Payment ')]</value>
      <webElementGuid>97c4c11f-c4e7-4e93-a311-c49d9d59214b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
