<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_Security-Question</name>
   <tag></tag>
   <elementGuidId>7d764466-f152-4214-8473-8365931542cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c21-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='registration-form']/div/mat-form-field/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#registration-form div >> internal:has-text=&quot;Security Question *&quot;i >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cea4493d-3581-4063-8562-5fce664aa0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c21-16</value>
      <webElementGuid>6f49af2e-021b-4c70-9a50-999094ef544a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Security Question  *</value>
      <webElementGuid>8dbefc38-1eb9-47fa-8656-124351fea0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-form&quot;)/div[@class=&quot;security-container&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c21-16 mat-accent mat-form-field-type-mat-select mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label ng-pristine ng-invalid ng-star-inserted mat-form-field-invalid ng-touched mat-form-field-hide-placeholder&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c21-16&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c21-16&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c21-16&quot;]</value>
      <webElementGuid>bd4e2e27-adbb-4ab5-8137-e0e3d7f583a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='registration-form']/div/mat-form-field/div/div/div[3]</value>
      <webElementGuid>259c5658-7f73-4c1e-bfc5-1ff0321ab4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Repeat Password'])[1]/following::div[19]</value>
      <webElementGuid>4bf39e28-aea4-4ceb-93b4-c505f14f6a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a security question.'])[1]/preceding::div[5]</value>
      <webElementGuid>5c1d18e7-6c86-4927-aed8-5c36048c37de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/mat-form-field/div/div/div[3]</value>
      <webElementGuid>a0a38812-bb02-4b1d-bb5e-7fa2588b5f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Security Question  *' or . = ' Security Question  *')]</value>
      <webElementGuid>e6c5792d-c5a5-42c5-82b8-7d325153cece</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
